### PR TITLE
about page responds to small devices

### PR DESCRIPTION
**Pull request by RuthAnn1**

### CODE REVIEW

**Comment by dinaolmelak** [comment]
Way to go! @RuthAnn1 🙂 `A++` It is looking better 👍🏽

**Review by dinaolmelak — APPROVED** [review]

**Comment by RuthAnn1** [comment]
Thanks.  Got the easy ones done.  The next few pages will take me a bit

**Comment by dinaolmelak** [comment]
All or nothing right  👀 @RuthAnn1

**Comment by RuthAnn1** [comment]
haha very true

**Pull request merged**
