### PR TITLE
change font

### PR DESCRIPTION
**Pull request by Kendiya242**
change fonts for all pages

### CODE REVIEW

**Comment by Kendiya242** [comment]
I will change font for create events, organization board and create signup later this afternoon

**Review by dinaolmelak — APPROVED** [review]
Looks Much Better @Kendiya242 ! Thank you for the changes! 😁 Please consider using the issue templates to create more `Frontend` label tickets and make the front end much more nicer.

**Comment by dinaolmelak** [comment]
Looks Much Better @Kendiya242 ! Thank you for the changes! 😁 Please consider using the issue templates to create more `Frontend` label tickets and make the front end much nicer.

**Review by RuthAnn1 — APPROVED** [review]
Looks good to me

**Pull request merged**
