### PR TITLE
feature: Added Search bar

### PR DESCRIPTION
**Pull request by dinaolmelak**
I added the search bar; However, I am still working on the styling to stretch out the search_bar.

### CODE REVIEW

**Comment by dinaolmelak** [comment]
@Eco-Friends-Connect/everyone I have added Sass on through this PR; There is a `styles.scss` file contained in styles that we would be using for global styling. We can proceed with component-based styling also.

**Review by Donnyd88 — APPROVED** [review]
LGTM. Do you want to keep the commented out styles in for later or should those be removed?

**Review by RuthAnn1 — APPROVED** [review]
Looks good to me

**Comment by dinaolmelak** [comment]
@Donnyd88 my styling where conflicting with the styles of the index.css and if we remove that index.css it will also affect the styles you made @Donnyd88

**Comment by Donnyd88** [comment]
Some of the global ones were, but yours weren't. Whatever you want to do with them is good.

**Comment by dinaolmelak** [comment]
I do think we should remove it. Cause all our global stylings should be in the styles.scss file

**Comment by dinaolmelak** [comment]
I'll go ahead and do that in my next commit

**Pull request merged**
