### PR TITLE
homepage responsiveness fixed

### PR DESCRIPTION
**Pull request by RuthAnn1**

### CODE REVIEW

**Comment by dinaolmelak** [comment]
@RuthAnn1 ,  I see that your branch name is very long, that is a recipe for disaster. cause a little misspelling can have you wasting time. and yeah it is misspelled there 😅

**Comment by RuthAnn1** [comment]
noted... am I ok to merge?

**Comment by dinaolmelak** [comment]
I noticed the following @RuthAnn1 :
1. Is it possible to have the `nav bar` fixed to the top while scrolling down.
2 Also it does not let me click the `how it works` button when I am on an `iPhone XR`

**Comment by RuthAnn1** [comment]
You want the nav bar to move when scrolling?

**Comment by RuthAnn1** [comment]
At the moment it doesn't.

**Comment by dinaolmelak** [comment]
On `iPhone XR` the navbar move up when swiping up

**Comment by RuthAnn1** [comment]
You want it to not be fixed on the top correct?

**Comment by dinaolmelak** [comment]
I want it to be fixed in view. So that when I swipe up the Hamburger menu does not go up with the content. But If that is a design preference everyone is ok with, I am good with it.

**Comment by RuthAnn1** [comment]
I fixed the footer and the nav bar is looking correct.

**Comment by RuthAnn1** [comment]
The nav bar now moves and the footer is fixed

**Comment by dinaolmelak** [comment]
Yes! that was what I meant @RuthAnn1 for the nav bar! It no longer moves with the content

**Comment by dinaolmelak** [comment]
But the footer moves

**Comment by RuthAnn1** [comment]
You want the footer to move like the nav bar?

**Comment by RuthAnn1** [comment]
@dinaolmelak  is this looking better.  I have the footer moving like the navbar does.

**Comment by dinaolmelak** [comment]
yap! Perfect!, lol even tho we define moving differently, you understood me 😅 @RuthAnn1

**Review by dinaolmelak — APPROVED** [review]
LGTM

**Pull request merged**
