### PR TITLE
Organization dashboard

### PR DESCRIPTION
**Pull request by dinaolmelak**
I was having difficulties and was taking a long time for adding the `rope` to dangle the buttons from. Below is how it looks (sorry about the gif quality)
quicklook

### CODE REVIEW

**Review by RuthAnn1 — COMMENTED** [review]
Do we need to change how the design is?

**Comment by dinaolmelak** [comment]
I went for designing it the same way as the `2D artiest` from Figma

**Comment by dinaolmelak** [comment]
The reason I did not add the `co-org link` is because it is not part of the MVP

**Comment by RuthAnn1** [comment]
I agree on keeping the co-org link off since its not part of the MVP.  The gif makes the spacing look odd with the buttons like a lot of white space.  That is the only thing I have noticed.  otherwise it looks good to me.

**Comment by dinaolmelak** [comment]
To fill up the White space, we can either increase the size of the buttons or change the design completely. I felt bad about doing a different design considering that your `2D artist` came up with that design and that was what we had for our `Figma` prototype.

**Comment by RuthAnn1** [comment]
No need to feel bad about making a different design.  I'm up for anything.  My artist just doesn't have time to redesign pages.  So if we want to go a different route we just need to make the deign ourselves.  Did you want me to add the svg to the assets so we have access to the editable file?

**Pull request merged**
