### PR TITLE
Feature: Added get badges backend route.

### PR DESCRIPTION
**Pull request by dinaolmelak**
- I added a new table called `org-badge`. This table stores the relationship between an organization and it's badges.

## Getting the badges:
To get the badges the Backend does the following:
1. Gets the `user.uid` (if not signed in returns unauthorized)
2. Gets `membership` of the user to access the `orgId`
3. Gets `org_badge` using `orgId` to get the badges associated with that organization to access the `badgeId`.
4. Find the badges that match the `badgeId` in the list of badges 
5. Finally, returns that as the data.

## Here is a preview of how the output response looks.
Screenshot 2024-07-30 at 10 48 39 in the morning

### CODE REVIEW

**Comment by dinaolmelak** [comment]
Considering that the tokens may expire when sitting in the `MongoDB` , I have opted to getting new downloadUrl everytime the badges are being retrieved.

**Review by Donnyd88 — APPROVED** [review]
LGTM

**Review by RuthAnn1 — APPROVED** [review]
Looks good

**Comment by dinaolmelak** [comment]
Thank you @Donnyd88, @RuthAnn1

**Pull request merged**
