### PR TITLE
Change/signup font

### PR DESCRIPTION
**Pull request by Kendiya242**
hello team I have edit the signup.module.scss for the signup title. For the signup.jsx under return i have kept this line <h1 className={styles.signup}>Sign Up</h1>  and  just added the font size, style, weight and family under the .signup{  in the signup.module.scss to get the font to display.

### CODE REVIEW

**Review by dinaolmelak — APPROVED** [review]
Yeah, I can see the font is changed.

**Comment by Kendiya242** [comment]
can i merge once this PR is approved by everyone else

**Comment by dinaolmelak** [comment]
@Kendiya242 , update your branch first

**Comment by dinaolmelak** [comment]
Good work @Kendiya242

**Comment by dinaolmelak** [comment]
@Kendiya242

**Comment by dinaolmelak** [comment]
@Kendiya242

**Comment by dinaolmelak** [comment]
@Kendiya242

**Comment by dinaolmelak** [comment]
@Kendiya242  Testing Github 🐛

**Comment by dinaolmelak** [comment]
@Kendiya242  this is another test

**Pull request merged**
